source 'https://rubygems.org'

ruby '2.3.0'
gem 'cucumber'
gem 'capybara'
gem 'selenium-webdriver'
gem 'rspec', :require => 'spec'
gem 'rspec-expectations'
gem 'appium_lib'
gem 'httparty'
gem 'dotenv'
gem 'foreman'
gem 'rake'
gem 'byebug'
